### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by inelukipg** [vovayatsyuk/magento2-alsoviewed#4]
Hi @vovayatsyuk 
Are you still developing this module?

**Comment by vovayatsyuk** [comment]
Hi @inelukipg 

Yep, I'm still in.

**Comment by inelukipg** [comment]
Great! 
Is it working with Full Page Cache enabled? 
Is it compatible with Magento 2.1.3 / 2.1.4?

**Comment by vovayatsyuk** [comment]
Yes, sure. It's a stable release for magento 2.1.*

**Comment by inelukipg** [comment]
Ok great, 
Is it working with Full Page Cache enabled?

**Comment by vovayatsyuk** [comment]
Yes
