### ISSUE TITLE
Got error when use with database with prefix

### ISSUE THREAD

**Issue by snowleo208** [vovayatsyuk/magento2-alsoviewed#5]
Hi, I just installed this module in my development and I have a prefix in my database. After I enable this module and try to access it in admin's log/relations, I got this error:

> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.catalog_product_entity_varchar' doesn't exist, query was: SELECT COUNT(*) FROM `mg2_alsoviewed_relation` AS `main_table` INNER JOIN `catalog_product_entity_varchar` AS `product_name` ON product_id = product_name.entity_id INNER JOIN `catalog_product_entity_varchar` AS `related_product_name` ON related_product_id = related_product_name.entity_id WHERE (product_name.store_id = 0) AND (product_name.attribute_id = '71') AND (related_product_name.store_id = 0) AND (related_product_name.attribute_id = '71')

My settings:
Magento: 2.2.6
magento2-alsoviewed: 1.1.0

Are there any way to fix this issue? Thank you!

**Comment by vovayatsyuk** [comment]
Hi, 

Try to apply this fix: https://github.com/vovayatsyuk/magento2-alsoviewed/commit/2f1629b81936ee8cf6059cb2d6a5129782bfa2f6

**Comment by snowleo208** [comment]
Hi, it works and I can view log and relation in admin now. Thank you so much!
